### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by aravindprasad** [miladrayka/ET_Score#1]
```
~/ET_Score$ python predict.py -m et_score.sav -d example/structures/1a1e
Traceback (most recent call last):
  File "predict.py", line 57, in <module>
    feature.compute()
  File "/home/username/ET_Score/generate_feature.py", line 94, in compute
    ligand_path = glob.glob(protein_folder+"/"+"*.mol2")[0]
```
The problem is in lines 94 and 96
Line 94: ```ligand_path = glob.glob(protein_folder+"\\"+"*.mol2")[0]```
Line 96: ```protein_path = glob.glob(protein_folder+"\\"+"*.pdb")[0]```
When executed using the path "example/structures/1a1e", the value of "protein_folder" is 'example/structures/1a1e/1a1e_ligand.mol2" and in this case lines 94 and 96 are wrong logically.

As I go through the code, if I figure out the error in logic, I will post the solution (and code)

**Comment by miladrayka** [comment]
> 
> 
> ```
> ~/ET_Score$ python predict.py -m et_score.sav -d example/structures/1a1e
> Traceback (most recent call last):
>   File "predict.py", line 57, in <module>
>     feature.compute()
>   File "/home/username/ET_Score/generate_feature.py", line 94, in compute
>     ligand_path = glob.glob(protein_folder+"/"+"*.mol2")[0]
> ```
> 
> The problem is in lines 94 and 96
> Line 94: `ligand_path = glob.glob(protein_folder+"\\"+"*.mol2")[0]`
> Line 96: `protein_path = glob.glob(protein_folder+"\\"+"*.pdb")[0]`
> When executed using the path "example/structures/1a1e", the value of "protein_folder" is 'example/structures/1a1e/1a1e_ligand.mol2" and in this case lines 94 and 96 are wrong logically.
> 
> As I go through the code, if I figure out the error in logic, I will post the solution (and code)


Type this one in cmd:

`~/ET_Score$ python predict.py -m et_score.sav -d example/structures/`

Path directory should be like this ` ~/example/structures/. `
